name: docker action file

on: [ push ]

jobs:
  run-docker-container-registry-image:
   runs-on: ${{ vars.RUNNER_IMAGE }}
   steps:
     - name: checkout to repository
       uses: actions/checkout@v2
   container:
    image: ghcr.io/test-organization-package/ci-cd-fend:1.0
    credentials:
      username: ${{ github.actor }}
      password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
