name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
      age:
        description: 'Your age'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greetings: ${{ steps.greet.outputs.greetings }}
    steps:
      - name: Greet
        id: greet
        run: |
          greetings="Hello, ${{ github.event.inputs.name }}! You are ${{ github.event.inputs.age }} years old."
          echo "::set-output name=greetings::$greetings"

  after-greet:
      needs: greet
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.greetfile.outputs.all-greets }}
      steps:
        - name: After greet
          id: greetfile
          env:
            GREETINGS: ${{ needs.greet.outputs.greetings }}
          run: |
             echo "$GREETINGS now happy birthday" >> greeting.txt
             echo "::set-output name=all-greets::$(cat greeting.txt)"

  show-all:
    needs: after-greet
    runs-on: ubuntu-latest
    steps:
      - name: Display all greetings
        env:
          ALL_GREETS: ${{ needs.after-greet.outputs.output1 }}
        run: echo "$ALL_GREETS"

        


