name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
      age:
        description: 'Your age'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest
    outputs:
      greetings: ${{ steps.greet.outputs.greetings }}
    steps:
      - name: Greet
        id: greet
        run: |
          greetings="Hello, ${{ github.event.inputs.name }}! You are ${{ github.event.inputs.age }} years old."
          echo "::set-output name=greetings::$greetings"

  after-greet:
    needs: greet
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.greetfile.outputs.all-greets }}
    strategy:
      matrix:
        name: [ vivek, rohit, laddu ]
        surname: [ rachamalla, ammababoi ]
        exclude:
         - name: laddu
           surname: rachamalla
    steps:
      - name: After greet
        id: greetfile
        env:
          GREETINGS: ${{ needs.greet.outputs.greetings }}
        run: |
          echo "$GREETINGS now happy birthday" >> greeting.txt &&
          echo "$all-greets=$( cat greetin.yxy )" >> $GITHUB_OUTPUT
  shoew-all:
    needs: after-greet
    runs-on: ubantu-latest
    steps:
      - name: display all greetings
        env:
          ALL_GREETS: ${{ needs.after-greet.outputs.output1 }}
        run: echo "$ALL_GREETS"
        


