name: run test cases
run-name: workflow triggered by ${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  read-outpits:
    needs: [ run-testcases ]
    runs-on: ubuntu-20.4

    steps:
      - run: echo ${{ needs.run-testcases.outputs.test_output }}
     
  run-testcases:
    runs-on: ubuntu-20.4
    outputs:
      test_output: ${{ steps.tests.outputs }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - id: tests
        name: Run tests
        run: npm test
